server:
  port: 8090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 9715120018
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update